export const DATA_LOAD_REQUEST = 'DATA_LOAD_REQUEST'
export const DATA_LOAD_SUCCESS = 'DATA_LOAD_SUCCESS'
export const DATA_LOAD_FAILURE = 'DATA_LOAD_FAILURE'

export const CHANGE_PAGE = 'CHANGE_PAGE'
export const CHANGE_LIMIT = 'CHANGE_LIMIT'

export const DELETE_COMPANY = 'DELETE_COMPANY'
